---
repos:
  - repo: local
    hooks:
      - id: cfn-lint
        name: cfn-lint
        entry: cfn-lint
        language: python
        files: coudformation/templates/.*\.yml$
  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: python
        types: [file, yaml]
