---
AWSTemplateFormatVersion: '2010-09-09'
Description: ec2 instance stack

Parameters:
  Environment:
    Type: String
    Description: Enter prefix that should be used for tags.
    Default: development

  AmiId:
    Type: AWS::EC2::Image::Id
    Default: ami-04ac1ccf3fe61134b
  InstanceType:
    Type: String
    Default: t3.medium
  VolumeSize:
    Type: Number
    Default: 50
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances.
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Default: default

  IsEnableTerminationProtection:
    Type: String
    Description: Enable termination protection for EC2 instances.
    Default: false

Resources:
  Instance01:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: !Ref VolumeSize
            VolumeType: gp2
      CreditSpecification:
        CPUCredits: standard
      DisableApiTermination: !Ref IsEnableTerminationProtection
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      PropagateTagsToVolumeOnCreation: true
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${Environment}-public-sg
      SubnetId:
        Fn::ImportValue: !Sub ${Environment}-subnet-public-a
      UserData:
        Fn::Base64: |
          <powershell>
          $url = "https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"
          $file = "$env:TEMP\ConfigureRemotingForAnsible.ps1"

          Invoke-WebRequest $url -OutFile $file

          powershell.exe -ExecutionPolicy ByPass -File $file
          </powershell>
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref Environment, instance01]]

  Instance01Eip:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Instance01
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref Environment, instance01]]

Outputs:
  Instance01:
    Value: !Ref Instance01
    Export:
      Name: !Join ['-', [!Ref Environment, Instance01]]
